debug: False
data:
 dataset_folder: /botanic
 evalset_folder: /botanic/testing
eval:
  eval_mode: 0
  similarity: cosine
  batch_size: 32
  intra_files: [5-03.pickle,5-06.pickle] # intra
  database_files: [Venman_evaluation_database.pickle, Karawatha_evaluation_database.pickle]
  query_files: [Venman_evaluation_query.pickle, Karawatha_evaluation_query.pickle]
  world_thresh: 3
  time_thresh: 100
  save_embeddings: '/A_dataset'
  set_names: ['01','02','03','04']
  make_graph_in_eval: False